// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDG4ky0jU2ddC4iIleW5XKbejsoIOMRyo',
    appId: '1:1037402011718:android:be3f72b81cd98ed4',
    messagingSenderId: '1037402011718',
    projectId: 'klikfilm-app',
    databaseURL: 'https://klikfilm-app.firebaseio.com',
    storageBucket: 'klikfilm-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALas468enN5ZB9QW1OSiwlY6_r9Gwqvhw',
    appId: '1:1037402011718:ios:8bcba463e58738a5',
    messagingSenderId: '1037402011718',
    projectId: 'klikfilm-app',
    databaseURL: 'https://klikfilm-app.firebaseio.com',
    storageBucket: 'klikfilm-app.appspot.com',
    androidClientId: '1037402011718-1uofga9c9se4h8vlti834g0f4igthooc.apps.googleusercontent.com',
    iosClientId: '1037402011718-8b1vu8crgjkk26dl4cb4nj7cfdph521c.apps.googleusercontent.com',
    iosBundleId: 'falcon.klifkfilm',
  );
}
